#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
   path: /
   controller: App\Controller\MSPController::index

add_project:
   path: /add
   controller: App\Controller\MSPController::add

read_project:
   path: /read/{id}
   controller: App\Controller\MSPController::read

edit_project:
   path: /edit/{id}
   controller: App\Controller\MSPController::edit

card:
   path: /card
   controller: App\Controller\MSPController::card

delete_project:
   path: /delete/{id}
   